name: steered-marigold
channels:
  - pytorch
  - nvidia
  - conda-forge
  - xformers
  - defaults
dependencies:
  - python=3.10.11
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - torchvision=0.16.2=py310_cu121
  - diffusers=0.25.0
  - xformers