#!/bin/bash

python3 -m steeredmarigold.validate_steeredmarigold \
    --pretrained-model-name-or-path "stabilityai/stable-diffusion-2" \
    --checkpoint "prs-eth/marigold-depth-v1-0" \
    --output-dir "${MODELS_DIR}/final5/steeredmarigold-x0-alpha0.1-preserve0.05-nyu448x608-interp0.05dilate13" \
    --val-dataset-name "steeredmarigold.dataset.Nyuv2" \
    --val-preprocessing "steeredmarigold.preprocessing.evaluate_naive_lidar_metric" \
    --val-dataset-set "test" \
    --val-data-dir "${DATASETS_DIR}/nyu-v2/" \
    --center-crop-height 448 \
    --center-crop-width 608 \
    --evaluation-function "steeredmarigold.evaluate.mde_to_dc" \
    --denoising-steps 50 \
    --weight-dtype "fp32" \
    --min-depth 0 \
    --compute-metrics \
    --store-raw \
    --save-visualizations \
    --steering-factor 0.1 \
    --naive-lidar 0.05 \
    --neighborhood 13

python3 -m steeredmarigold.validate_steeredmarigold \
    --pretrained-model-name-or-path "stabilityai/stable-diffusion-2" \
    --checkpoint "prs-eth/marigold-depth-v1-0" \
    --output-dir "${MODELS_DIR}/final5/steeredmarigold-x0-alpha0.2-preserve0.05-nyu448x608-interp0.05dilate13" \
    --val-dataset-name "steeredmarigold.dataset.Nyuv2" \
    --val-preprocessing "steeredmarigold.preprocessing.evaluate_naive_lidar_metric" \
    --val-dataset-set "test" \
    --val-data-dir "${DATASETS_DIR}/nyu-v2/" \
    --center-crop-height 448 \
    --center-crop-width 608 \
    --evaluation-function "steeredmarigold.evaluate.mde_to_dc" \
    --denoising-steps 50 \
    --weight-dtype "fp32" \
    --min-depth 0 \
    --compute-metrics \
    --store-raw \
    --save-visualizations \
    --steering-factor 0.2 \
    --naive-lidar 0.05 \
    --neighborhood 13

python3 -m steeredmarigold.validate_steeredmarigold \
    --pretrained-model-name-or-path "stabilityai/stable-diffusion-2" \
    --checkpoint "prs-eth/marigold-depth-v1-0" \
    --output-dir "${MODELS_DIR}/final5/steeredmarigold-x0-alpha0.3-preserve0.05-nyu448x608-interp0.05dilate13" \
    --val-dataset-name "steeredmarigold.dataset.Nyuv2" \
    --val-preprocessing "steeredmarigold.preprocessing.evaluate_naive_lidar_metric" \
    --val-dataset-set "test" \
    --val-data-dir "${DATASETS_DIR}/nyu-v2/" \
    --center-crop-height 448 \
    --center-crop-width 608 \
    --evaluation-function "steeredmarigold.evaluate.mde_to_dc" \
    --denoising-steps 50 \
    --weight-dtype "fp32" \
    --min-depth 0 \
    --compute-metrics \
    --store-raw \
    --save-visualizations \
    --steering-factor 0.3 \
    --naive-lidar 0.05 \
    --neighborhood 13

python3 -m steeredmarigold.validate_steeredmarigold \
    --pretrained-model-name-or-path "stabilityai/stable-diffusion-2" \
    --checkpoint "prs-eth/marigold-depth-v1-0" \
    --output-dir "${MODELS_DIR}/final5/steeredmarigold-x0-alpha0.4-preserve0.05-nyu448x608-interp0.05dilate13" \
    --val-dataset-name "steeredmarigold.dataset.Nyuv2" \
    --val-preprocessing "steeredmarigold.preprocessing.evaluate_naive_lidar_metric" \
    --val-dataset-set "test" \
    --val-data-dir "${DATASETS_DIR}/nyu-v2/" \
    --center-crop-height 448 \
    --center-crop-width 608 \
    --evaluation-function "steeredmarigold.evaluate.mde_to_dc" \
    --denoising-steps 50 \
    --weight-dtype "fp32" \
    --min-depth 0 \
    --compute-metrics \
    --store-raw \
    --save-visualizations \
    --steering-factor 0.4 \
    --naive-lidar 0.05 \
    --neighborhood 13
